# docker-compose.yaml

version: '3.8'

services:
  db:
    image: postgres:13-alpine
    # volumes:
      # - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=core-api-db
    env_file:
      - ./.env
      
  core-api:
    build: ./core-api
    volumes:
      - ./core-api/:/usr/src/app/
    ports:
      - 5001:5000
    env_file:
      - ./.env
    depends_on:
      - db

# volumes:
#   postgres_data: